# Generated by Django 3.1.5 on 2021-02-27 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
