# Generated by Django 3.1.5 on 2021-03-01 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210227_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('subject', models.CharField(max_length=20, verbose_name='Subject')),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='title',
            new_name='subject',
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime1', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('datetime2', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('datetime3', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
