# Generated by Django 3.1.5 on 2021-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210301_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='content',
            new_name='teacher',
        ),
    ]
