# Generated by Django 3.1.5 on 2021-03-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210301_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='aTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='Subject')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
            ],
        ),
        migrations.AlterField(
            model_name='slots',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ateacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
