# Generated by Django 3.1.5 on 2021-03-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210301_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ateacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ateacher'),
        ),
    ]
